// SOTS_DATA — Sermon On The Shoal
// Auto-generated by parse_sots.js on 2026-05-07T17:51:28.267Z
// Sections: 10 (α, β, γ, δ, ε, ζ, η, θ, ι, κ)

var SOTS_DATA = {
  "sots": {
    "title": "Sermon On The Shoal",
    "start": "__menu__",
    "order": [
      "__menu__",
      "α",
      "β",
      "γ",
      "δ",
      "ε",
      "ζ",
      "η",
      "θ",
      "ι",
      "κ"
    ],
    "sections": {
      "α": [
        "<p class=\"narrative drop-cap\"><strong>α — Parábola de los Bajíos</strong></p>",
        "<p class=\"narrative\">Durante vuestra búsqueda del Virtuario , os habéis reunido con los Seguidores locales de Areté . Mientras esperáis para hablar con ellos, captáis un fragmento de uno de los famosos «Sermones en los Bajíos», una colección de enseñanzas del Virtuario , tal como las relata uno de los sabios:</p>",
        "<p class=\"narrative\">«¡Escuchad! Si un niño contemplara solo la superficie del mar, pensaría que es plana y simple, y completa. Contempla, la totalidad del mar. Sin embargo, si ese mismo niño mirara bajo la superficie, se aterrorizaría ante las profundidades insondables, se perdería en su vasta oscuridad, y se ahogaría. El niño débil no llega al mar, y el temerario se ahoga. El dedicado permanece en los bajíos y es bautizado por ellos.»</p>",
        "<p class=\"narrative\">Y cuando le preguntaron sobre ello, les dijo: «Una parábola es como la superficie, mientras que su significado son las profundidades.» Y cuando aun así preguntaron, dijo: «Vivimos en un mundo de mentiras y verdades superficiales, que hacen nuestras vidas más fáciles, pero que en última instancia nos condenan. Sin embargo, si de pronto nos enfrentáramos a la verdadera Verdad del mundo, Areté , correríamos asustados o nos ahogaríamos en su enormidad. Así, primero necesitamos desafiar los bajíos y aprender que podemos nadar, antes de zambullirnos.»</p>",
        "<p class=\"game-note\">Un único Argonauta gana 1 ficha de Dolor. Un único Argonauta puede realizar una Disyunción Consciente (ver el Evento Especial Disyunción Consciente).</p>"
      ],
      "β": [
        "<p class=\"narrative drop-cap\"><strong>β — Parábola del Buscador de Perlas</strong></p>",
        "<p class=\"narrative\">Durante vuestra búsqueda del Virtuario , os habéis reunido con los Seguidores locales de Areté . Mientras esperáis para hablar con ellos, captáis un fragmento de uno de los famosos «Sermones en los Bajíos», una colección de enseñanzas del Virtuario , tal como las relata uno de los sabios:</p>",
        "<p class=\"narrative\">«¡Escuchad! Contemplad a un buscador de perlas nadando fuera de los bajíos. Cuanto más lejos va, más probable es que encuentre lo que busca. Sin embargo, cuanto más lejos va, más profundo y traicionero es el mar y sus profundidades. El buceador débil permanece en los bajíos, y el temerario se ahoga. El buceador dedicado regresa con su captura.»</p>",
        "<p class=\"game-note\">Un único Argonauta gana 1 ficha de Dolor. Puedes generar una AE-Sirena en el Mapa de Viaje.</p>"
      ],
      "γ": [
        "<p class=\"narrative drop-cap\"><strong>γ — Parábola de la Lucha</strong></p>",
        "<p class=\"narrative\">Durante vuestra búsqueda del Virtuario , os habéis reunido con los Seguidores locales de Areté . Mientras esperáis para hablar con ellos, captáis un fragmento de uno de los famosos «Sermones en los Bajíos», una colección de enseñanzas del Virtuario , tal como las relata uno de los sabios:</p>",
        "<p class=\"narrative\">«¡Mis Seguidores de Areté ! Habéis visto la superficie, desafiado los bajíos y os habéis aventurado en las profundidades, y aprendido muchísimas cosas sobre el mundo. Y ahora podríais preguntar, ¿qué le queda al Maestro por enseñar y al Aprendiz por aprender? A esos, yo preguntaría a cambio: ¿cuánto tiempo podéis contener la respiración? ¿A qué profundidad podéis bucear?»</p>",
        "<p class=\"narrative\">Y cuando más tarde se le pidió que explicara sus pensamientos, dijo: «Así como entrenáis vuestros pulmones, así también deberíais entrenar vuestra mente y espíritu. Y tal como los pulmones arden sin aire, antes de expandirse, así también dolerán vuestra mente y espíritu. Aprended mediante esta lucha.»</p>",
        "<p class=\"game-note\">Un único Argonauta gana 1 ficha de Dolor. Puedes añadir una Simulación de Batalla Mnestis (Titán X) a la Línea Temporal, a 2 días de ahora.</p>"
      ],
      "δ": [
        "<p class=\"narrative drop-cap\"><strong>δ — Pensamientos en Cosas</strong></p>",
        "<p class=\"narrative\">Durante vuestra búsqueda del Virtuario , os habéis reunido con los Seguidores locales de Areté . Mientras esperáis para hablar con ellos, captáis un fragmento de uno de los famosos «Sermones en los Bajíos», una colección de enseñanzas del Virtuario , tal como las relata uno de los sabios:</p>",
        "<p class=\"narrative\">«Cuando queráis atraer Areté a vuestra vida, aseguraos de que vuestras acciones no contradigan vuestros deseos. Pensad en lo que habéis pedido, y aseguraos de que vuestras acciones reflejen lo que esperáis recibir, y de que no contradigan lo que habéis pedido. Actuad como si lo estuvierais recibiendo. Haced exactamente lo que haríais si lo estuvierais recibiendo hoy, y emprended acciones en vuestra vida para reflejar esa poderosa expectativa. Haced espacio para recibir vuestros deseos, y, al hacerlo, estáis enviando esa poderosa señal de expectativa. Y volverá a vosotros, como el mar durante una marea.»</p>",
        "<p class=\"game-note\">Gana 5 fichas de Dolor como grupo para ganar una carta de Equipo generado por Mnestis aleatoria.</p>"
      ],
      "ε": [
        "<p class=\"narrative drop-cap\"><strong>ε — Verdad de la Vida</strong></p>",
        "<p class=\"narrative\">Durante vuestra búsqueda del Virtuario , os habéis reunido con los Seguidores locales de Areté . Mientras esperáis para hablar con ellos, captáis un fragmento de uno de los famosos «Sermones en los Bajíos», una colección de enseñanzas del Virtuario , tal como las relata uno de los sabios:</p>",
        "<p class=\"narrative\">«Muchos de vosotros sentís que sois víctimas en la vida, y a menudo señalaréis acontecimientos pasados, quizá crecer con un padre abusivo o en una familia disfuncional. La mayoría de las familias son disfuncionales, ¡incluso los Olímpicos lo eran! De pronto, no sois tan únicos. Mi madre estuvo ausente. Mi padre fue abusivo. Fui abandonado a los seis años. Esa es la historia de casi todo el mundo de una forma u otra. La verdadera pregunta es, ¿qué vais a hacer ahora? ¿Elegiréis Areté ? Porque podéis seguir concentrándoos en vuestras desgracias, o podéis concentraros en lo que queréis. Y cuando la gente empieza a concentrarse en lo que quiere, lo que no quiere se desvanece, y lo que quiere se expande, y la otra parte desaparece. ¿Queréis Areté ? Entonces elegidla. Soportad vuestro dolor. El único camino es hacia delante.»</p>",
        "<p class=\"game-note\">Un único Argonauta gana 2 fichas de Dolor. Un único Argonauta puede realizar una Disyunción Consciente (ver el Evento Especial Disyunción Consciente).</p>"
      ],
      "ζ": [
        "<p class=\"narrative drop-cap\"><strong>ζ — ¿Qué Es el Miedo?</strong></p>",
        "<p class=\"narrative\">Durante vuestra búsqueda del Virtuario , os habéis reunido con los Seguidores locales de Areté . Mientras esperáis para hablar con ellos, captáis un fragmento de uno de los famosos «Sermones en los Bajíos», una colección de enseñanzas del Virtuario , tal como las relata uno de los sabios:</p>",
        "<p class=\"narrative\">«El miedo es la serpiente marina que se desliza hasta nuestros corazones, y muerde a quienes intentan desenroscarla, hasta que inevitablemente se vuelve contra nosotros. El miedo enturbia nuestros pensamientos. El miedo deteriora nuestro juicio. El miedo nos vuelve tímidos, y débiles, y blandos, y estúpidos. El miedo es nuestro carcelero y juez, y verdugo. En el miedo, nos ahogamos. El miedo es el Oscuro de Abajo. El miedo es el obstáculo en nuestro camino hacia Areté , hacia el mundo real. Es el Guardián de la Puerta.»</p>",
        "<p class=\"game-note\">Un único Argonauta puede descartar cualquier carta de Condición. Puedes añadir una Simulación de Batalla Mnestis (Titán X) a la Línea Temporal, a 2 días de ahora.</p>"
      ],
      "η": [
        "<p class=\"narrative drop-cap\"><strong>η — ¿Por Qué Es el Miedo?</strong></p>",
        "<p class=\"narrative\">Durante vuestra búsqueda del Virtuario , os habéis reunido con los Seguidores locales de Areté . Mientras esperáis para hablar con ellos, captáis un fragmento de uno de los famosos «Sermones en los Bajíos», una colección de enseñanzas del Virtuario , tal como las relata uno de los sabios:</p>",
        "<p class=\"narrative\">«Nacemos solos y morimos solos. Todas esas conexiones que hacemos por el camino y que apreciamos y consideramos importantes y valiosas y recíprocas, no son más que meros fantasmas. Caminamos solos. Y aunque intentamos distraernos con trivialidades y baratijas y dicha transitoria, para no darnos cuenta, en lo profundo de nuestros corazones, lo sabemos. Solo hay tres cosas en el mundo que son reales: la muerte, el dolor y la verdad. Es a la muerte a lo que tememos. Y no podemos extirpar ese miedo porque está tejido en nuestra propia creación. La muerte es el Oscuro de Abajo. El miedo es el obstáculo en nuestro camino hacia Areté , hacia el mundo real. Es el Devorador de Almas.»</p>",
        "<p class=\"game-note\">Un Argonauta aleatorio gana 2 fichas de Dolor y la carta de Condición Miedo. Puedes generar una AE-Sirena en el Mapa de Viaje.</p>"
      ],
      "θ": [
        "<p class=\"narrative drop-cap\"><strong>θ — ¿Por Qué Es el Dolor?</strong></p>",
        "<p class=\"narrative\">Durante vuestra búsqueda del Virtuario , os habéis reunido con los Seguidores locales de Areté . Mientras esperáis para hablar con ellos, captáis un fragmento de uno de los famosos «Sermones en los Bajíos», una colección de enseñanzas del Virtuario , tal como las relata uno de los sabios:</p>",
        "<p class=\"narrative\">«La segunda de las tres cosas reales en el mundo es el Dolor, el Camino. El dolor llena el espacio entre el nacimiento y la muerte. Es la miseria a lo largo del camino, todo ese sufrimiento, físico pero más importante aún mental y espiritual, que nos atormenta. Estoy aquí para deciros que el dolor no es malo. El dolor no es malo. El dolor es un don. Nos moldea, nos templa, nos guía y nos libera. Hace la vida soportable, porque aparta nuestra atención del Miedo, el Devorador de Almas. La liberación del dolor es dicha eterna no transitoria, pero no habría dicha sin dolor. El dolor nos da propósito.»</p>",
        "<p class=\"game-note\">Un Argonauta aleatorio gana 2 fichas de Dolor y la carta de Condición Miedo. Otro Argonauta gana la carta de Condición Resuelto.</p>"
      ],
      "ι": [
        "<p class=\"narrative drop-cap\"><strong>ι — ¿Qué Es el Dolor?</strong></p>",
        "<p class=\"narrative\">Durante vuestra búsqueda del Virtuario , os habéis reunido con los Seguidores locales de Areté . Mientras esperáis para hablar con ellos, captáis un fragmento de uno de los famosos «Sermones en los Bajíos», una colección de enseñanzas del Virtuario , tal como las relata uno de los sabios:</p>",
        "<p class=\"narrative\">«El dolor conduce a la dicha eterna no transitoria, pero también es lo opuesto de la dicha eterna, porque el dolor se mueve y la dicha se aquieta. El movimiento es vida, la quietud es muerte. La muerte es Miedo, la primera cosa real del mundo.»</p>",
        "<p class=\"narrative\">«Y el Miedo, el Devorador de Almas, el Guardián de la Puerta, es grande, pues la muerte es real. El Oscuro de Abajo es real. Para matarlo, para hacerlo morir de hambre, para atravesar su umbral, para alcanzar Areté , la tercera cosa real en el mundo, que es el mundo, debe sufrirse un gran dolor.»</p>",
        "<p class=\"narrative\">«Cada uno de vosotros individualmente, y todos vosotros colectivamente, necesitáis sufrir dolor, un dolor tan grande que os haga desear la muerte. En ese deseo, finalmente conquistaréis al Miedo, el Devorador de Almas, el Guardián de la Puerta, el Umbral, y al conquistar el Miedo, finalmente seréis libres para experimentar la dicha que es Areté , la Verdad, la tercera cosa real en el mundo que es el mundo.»</p>",
        "<p class=\"game-note\">Un Argonauta aleatorio gana permanentemente Resiliencia al Dolor 1. Un único Argonauta puede realizar una Disyunción Consciente (ver el Evento Especial Disyunción Consciente).</p>"
      ],
      "κ": [
        "<p class=\"narrative drop-cap\"><strong>κ — ¿Qué Es la Esperanza?</strong></p>",
        "<p class=\"narrative\">Durante vuestra búsqueda del Virtuario , os habéis reunido con los Seguidores locales de Areté . Mientras esperáis para hablar con ellos, captáis un fragmento de uno de los famosos «Sermones en los Bajíos», una colección de enseñanzas del Virtuario , tal como las relata uno de los sabios:</p>",
        "<p class=\"narrative\">«La esperanza es una mentira. Nos engaña, nos desvía, nos hace bajar la guardia, nos hace reducir la marcha, nos hace detenernos, nos hace evitar el dolor, nos hace sucumbir al miedo. La esperanza es el Gran Embaucador.»</p>",
        "<p class=\"narrative\">«Abandonad toda esperanza. Aceptad vuestro dolor, físico, mental y, sobre todo, espiritual. Una vez que el dolor haya terminado con vosotros, nada quedará. Ni Miedo, ni Muerte, ni siquiera Dolor. Solo Areté , la Verdad, la tercera cosa real en el mundo que es el mundo que se convierte en la única cosa real en el mundo. Y estáis en paz.»</p>",
        "<p class=\"game-note\">Un Argonauta aleatorio gana 3 fichas de Dolor y la carta de Condición Miedo. Gana +1 <span class=\"ato-icon\">B</span> inevitable . Añade la Batalla El Diablo Mismo a la Línea Temporal, a 2 días de ahora.</p>"
      ],
      "__menu__": [
        "<h1 class=\"doc-title\">Sermon On The Shoal</h1><img class=\"menu-cover\" src=\"Imagenes/Sermon%20On%20The%20Shoals.png\" alt=\"Sermón en los Bajíos\"><div class=\"menu-list\"><div class=\"menu-chapter\" data-doc=\"sots\" data-sec=\"α\"><span class=\"menu-ch-title\">α — Parábola de los Bajíos</span></div><div class=\"menu-chapter\" data-doc=\"sots\" data-sec=\"β\"><span class=\"menu-ch-title\">β — Parábola del Buscador de Perlas</span></div><div class=\"menu-chapter\" data-doc=\"sots\" data-sec=\"γ\"><span class=\"menu-ch-title\">γ — Parábola de la Lucha</span></div><div class=\"menu-chapter\" data-doc=\"sots\" data-sec=\"δ\"><span class=\"menu-ch-title\">δ — Pensamientos en Cosas</span></div><div class=\"menu-chapter\" data-doc=\"sots\" data-sec=\"ε\"><span class=\"menu-ch-title\">ε — Verdad de la Vida</span></div><div class=\"menu-chapter\" data-doc=\"sots\" data-sec=\"ζ\"><span class=\"menu-ch-title\">ζ — ¿Qué Es el Miedo?</span></div><div class=\"menu-chapter\" data-doc=\"sots\" data-sec=\"η\"><span class=\"menu-ch-title\">η — ¿Por Qué Es el Miedo?</span></div><div class=\"menu-chapter\" data-doc=\"sots\" data-sec=\"θ\"><span class=\"menu-ch-title\">θ — ¿Por Qué Es el Dolor?</span></div><div class=\"menu-chapter\" data-doc=\"sots\" data-sec=\"ι\"><span class=\"menu-ch-title\">ι — ¿Qué Es el Dolor?</span></div><div class=\"menu-chapter\" data-doc=\"sots\" data-sec=\"κ\"><span class=\"menu-ch-title\">κ — ¿Qué Es la Esperanza?</span></div></div>"
      ]
    }
  }
};
